config_version = 1

[chat]
# enable global chat?
enable = true

# should the chat messages be echoed to velocity's console?
log_to_console = true

# should chat messages be passed through to the minecraft server?
# if enabled, it will show duplicate messages in the senders chat
passthrough = true

# should chat messages be parsed through minimessage?
# player will be able to use styles such as <rainbow>hello</rainbow> in their messages
parse_player_messages = true

# global chat format, you can use minimessage tags here.
format = "<<player>>: <message>"

[urls]
# should urls typed in chat be clickable?
clickable = true
# the regular expression used to determine whether something is a url
# test using https://regex101.com/ set to Java 8 and only the "g" (global) flag
pattern = "https?:\\/\\/\\S+"

[join]
# send a chat message when a player connects to velocity? Useful for fabric servers which dont already have a Join message.
enable = false
format = "<yellow><player> 加入了游戏</yellow>"

[quit]
# send a chat message when a player disconnects?
enable = true
format = "<yellow><player> 离开了游戏</yellow>"