config_version = 1

[chat]
# 是否启用全局聊天？
enable = true

# 是否把聊天信息输出到velocity的控制台？
log_to_console = true

# 是否把聊天信息传递给minecraft服务器？
# 如果启用，发送者的聊天框会显示重复的信息。
passthrough = true

# 是否把聊天信息解析为minimessage？
# 玩家可以在信息中使用样式，比如 <rainbow>hello</rainbow>。
parse_player_messages = true

# 全局聊天格式，你可以在这里使用minimessage标签。
format = "<<player>>: <message>"

[urls]
# 是否让聊天中输入的网址可以点击？
clickable = true
# 用来判断是否是网址的正则表达式。
# 可以使用 https://regex101.com/ 测试，选择Java 8并且只勾选"g"（全局）标志。
pattern = "https?:\\/\\/\\S+"

[join]
# 当玩家连接到velocity时，是否发送一条聊天信息？对于没有加入信息的fabric服务器很有用。
enable = false
format = "<yellow><player> 加入了游戏</yellow>"

[quit]
# 当玩家断开连接时，是否发送一条聊天信息？
enable = true
format = "<yellow><player> 离开了游戏</yellow>"

[ping]
# 在服务器列表检测服务器延迟时，是否显示所有连接到Velocity的玩家？
enable = true

[stp]
# 是否启用 /stp 命令？
enable = true
